const RoutesPath = {
  home: "/",
  login: "/login",
  templates: "/info",
  aboutUs: "/aboutUs",
  contactUspage: "/contactUspage",
  postJop: "/postJop",
  postJop1: "/find-freelancer",
  postJop2: "/work",
  postJop3: "/skills",
  jop: "/jobs",
  newJops: "/new-jops",
  savedJops: "/saved-jops",
  addCompany:"/addCompany",
  profileCompany: "/profileCompany",
  myCv: "/myCv",
  editPassword: "/editPassword",
  chatForFreelancer:"/chatForFreelancer",
  chatForCompany:"/chatForCompany",
  talants:"/talants",
  bestMatches:"/bestMatches",
  NewTalants:"/NewTalants",
  Saved:"/Saved",
  signUpPage:"/signUpPage",
  signUp:"/SignUp",
  complete:"/complete",
  companyCom:"/companyCom",
  jobModalPageView:"jobModalPageView",
};

export default RoutesPath